**Run the following two cells before you begin.**

In [1]:
%autosave 10

Autosaving every 10 seconds


In [2]:
import pandas as pd
import numpy as np

______________________________________________________________________
**First, import your data set and define the sigmoid function.**
<details>
    <summary>Hint:</summary>
    The definition of the sigmoid is $f(x) = \frac{1}{1 + e^{-X}}$.
</details>

In [3]:
# Import the data set
df = pd.read_csv("cleaned_data.csv")
df.head(10)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24      2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26     -1      2   
2  85698822-43f5      90000    2          2         2   34      0      0   
3  0737c11b-be42      50000    2          2         1   37      0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57     -1      0   
5  ceae2946-47e4      50000    1          1         2   37      0      0   
6  d3b8ce26-9c89     500000    1          1         2   29      0      0   
7  d6e1911b-54d0     100000    2          2         2   23      0     -1   
8  8421d3b3-2b54     140000    2          3         1   28      0      0   
9  62a2fd79-cd90      20000    1          3         2   35     -2     -2   

   PAY_3  PAY_4  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0     -1     -1  ...         0         0         0         0   
1      0      0  ...      1000      1000         0      2000   
2      0      0  ...      1000      1000      1000      5000   
3      0      0  ...      1200      1100      1069      1000   
4     -1      0  ...     10000      9000       689       679   
5      0      0  ...       657      1000      1000       800   
6      0      0  ...     38000     20239     13750     13770   
7     -1      0  ...         0       581      1687      1542   
8      2      0  ...       432      1000      1000      1000   
9     -2     -2  ...         0     13007      1122         0   

   default payment next month    EDUCATION_CAT  graduate school  high school  \
0                           1       university                0            0   
1                           1       university                0            0   
2                           0       university                0            0   
3                           0       university                0            0   
4                           0       university                0            0   
5                           0  graduate school                1            0   
6                           0  graduate school                1            0   
7                           0       university                0            0   
8                           0      high school                0            1   
9                           0      high school                0            1   

   others  university  
0       0           1  
1       0           1  
2       0           1  
3       0           1  
4       0           1  
5       0           0  
6       0           0  
7       0           1  
8       0           0  
9       0           0  

[10 rows x 30 columns]

In [4]:
# Define the sigmoid function
def sigmoid(x):
    y=1/(1+np.exp(-x))
    return y

**Now, create a train/test split (80/20) with `PAY_1` and `LIMIT_BAL` as features and `default payment next month` as values. Use a random state of 24.**

In [5]:
# Create a train/test split
from sklearn.model_selection import train_test_split
X = df[['PAY_1','LIMIT_BAL']].values
Y = df['default payment next month'].values
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=24,test_size=0.2)

______________________________________________________________________
**Next, import LogisticRegression, with the default options, but set the solver to `'liblinear'`.**

In [6]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear')
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

______________________________________________________________________
**Now, train on the training data and obtain predicted classes, as well as class probabilities, using the testing data.**

In [7]:
# Fit the logistic regression model on training data
model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
# Make predictions using `.predict()`
pred = model.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
# Find class probabilities using `.predict_proba()`
pred_prob = model.predict_proba(X_test)
pred_prob


array([[0.74826924, 0.25173076],
       [0.584297  , 0.415703  ],
       [0.79604453, 0.20395547],
       ...,
       [0.584297  , 0.415703  ],
       [0.82721498, 0.17278502],
       [0.66393435, 0.33606565]])

______________________________________________________________________
**Then, pull out the coefficients and intercept from the trained model and manually calculate predicted probabilities. You'll need to add a column of 1s to your features, to multiply by the intercept.**

In [10]:
# Add column of 1s to features
df['1s'] = 0
df


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24      2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26     -1      2   
2      85698822-43f5      90000    2          2         2   34      0      0   
3      0737c11b-be42      50000    2          2         1   37      0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57     -1      0   
5      ceae2946-47e4      50000    1          1         2   37      0      0   
6      d3b8ce26-9c89     500000    1          1         2   29      0      0   
7      d6e1911b-54d0     100000    2          2         2   23      0     -1   
8      8421d3b3-2b54     140000    2          3         1   28      0      0   
9      62a2fd79-cd90      20000    1          3         2   35     -2     -2   
10     b73c34fc-91cf     200000    2          3         2   34      0      0   
11     4777689a-5131     260000    2          1         2   51     -1     -1   
12     b814ac5c-3d88     630000    2          2         2   41     -1      0   
13     a17b23d4-357b      70000    1          2         2   30      1      2   
14     0d6f99ad-84e9     250000    1          1         2   29      0      0   
15     8f023df0-a9ea      50000    2          3         3   23      1      2   
16     cbf648a6-98aa      20000    1          1         2   24      0      0   
17     cb258690-8ea2     360000    2          1         1   49      1     -2   
18     f6f0307a-b75f     180000    2          1         2   29      1     -2   
19     47a4cdaa-aa20     130000    2          3         2   39      0      0   
20     834b2cac-750e     120000    2          2         1   39     -1     -1   
21     c1d1d0f2-6aec      70000    2          2         2   26      2      0   
22     66a293d5-6384     450000    2          1         1   40     -2     -2   
23     817396f7-aad1      90000    1          1         2   23      0      0   
24     275d9f10-f748      50000    1          3         2   23      0      0   
25     7784e5a8-a66c      60000    1          1         2   27      1     -2   
26     99ccbfaa-715b      50000    2          3         2   30      0      0   
27     72c682a7-c8af     230000    2          1         2   27     -1     -1   
28     a8eb0be8-23bb      50000    1          2         2   33      2      0   
29     3b76b111-03c1     100000    1          1         2   32      0      0   
...              ...        ...  ...        ...       ...  ...    ...    ...   
26634  22a584bc-ac83     150000    1          4         2   31      2      0   
26635  db2acf78-7f5d      20000    1          2         2   34      0      0   
26636  0b4f798d-f993     200000    1          2         1   33      0      0   
26637  af452e9d-d287     360000    1          1         1   34     -1     -1   
26638  a381d0b4-087a      80000    1          3         1   36      0      0   
26639  a40d8b62-0083     190000    1          1         1   37      0      0   
26640  acdb424a-32bd      50000    1          2         1   37      1      2   
26641  8dea83fa-2f50      40000    1          2         2   47      2      2   
26642  f2df66b1-ef3b     420000    1          1         2   34      0      0   
26643  6c7190e2-b3fe     310000    1          2         1   39      0      0   
26644  239a1d2e-f4f4     180000    1          1         1   32     -2     -2   
26645  2623fe20-6010      50000    1          3         2   42      0      0   
26646  af84788c-4c27      50000    1          2         1   44      1      2   
26647  207df2a7-7dd6      90000    1          2         1   36      0      0   
26648  429d2c82-67ae      20000    1          2         1   44     -2     -2   
26649  71ccca61-6306     240000    1          1         2   30     -2     -2   
26650  39b25a8c-193b     360000    1          1         2   35     -1     -1   
26651  aaf9f747-0646     130000    1          1         2   34      0      0   
26652  ef8a4bcd-79

In [14]:
# Get coefficients and intercepts from trained model
coef = model.coef_
inter = model.intercept_
print("Coefficients: ",coef)
print("Intercept: ", inter)

Coefficients:  [[ 8.27451187e-11 -6.80876727e-06]]
Intercept:  [-6.57647457e-11]


In [19]:
# Manually calculate predicted probabilities
theta_1 = model.coef_[0][0]
theta_2 = model.coef_[0][1]
a = X_test[:,0]
b = X_test[:,1]
x = theta_1*a + theta_2*b + inter
m_pred_prob = sigmoid(x)
sk_learn_pred_prob = pred_prob[:,1]
print(m_pred_prob)
if(all(m_pred_prob)== all(sk_learn_pred_prob)):
    print("Both probabilities are true")

[0.25173076 0.415703   0.20395547 ... 0.415703   0.17278502 0.33606565]
Both probabilities are true


______________________________________________________________________
**Next, using a threshold of `0.5`, manually calculate predicted classes. Compare this to the class predictions output by scikit-learn.**

In [21]:
# Manually calculate predicted classes
m_pred_prob
mask = list(m_pred_prob>0.5)
m_pred = []
for i in mask:
    if(i==False):
        m_pred.append(0)
    else:
        m_pred.append(1)
        
m_prediction = np.array(m_pred)
m_prediction


array([0, 0, 0, ..., 0, 0, 0])

In [22]:
# Compare to scikit-learn's predicted classes
m_prediction == pred


array([ True,  True,  True, ...,  True,  True,  True])

______________________________________________________________________
**Finally, calculate ROC AUC using both scikit-learn's predicted probabilities, and your manually predicted probabilities, and compare.**

In [23]:
# Use scikit-learn's predicted probabilities to calculate ROC AUC
from sklearn import metrics
roc_auc_sklearn=metrics.roc_auc_score(Y_test,sk_learn_pred_prob)
roc_auc_sklearn


0.627207450280691

In [25]:
# Use manually calculated predicted probabilities to calculate ROC AUC
roc_auc_manual=metrics.roc_auc_score(Y_test,m_pred_prob)
roc_auc_manual

0.627207450280691

We achieve the same ROC AUC manually as well as using scikit-learn